WebApp/Areas/Admin/Controllers/CommonController.cs
using WebApp.Infrastructure;
using DomainLogic.Interfaces.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Areas.Admin.Controllers
{
    public class CommonController : Controller
    {

        public ActionResult ApplicationFiles()
        {
            return View();
        }

    }
}

WebApp/Areas/Default/Controllers/CommonController.cs
using WebApp.Controllers;
using DomainLogic.Interfaces;
using DomainLogic.Interfaces.Services;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using DomainLogic.Infrastructure;
using DomainLogic.Models;
using DomainLogic.Models.Settings;
using DomainLogic.Infrastructure.Attributes;
using DomainLogic.Infrastructure.Utils;
using DomainLogic.Infrastructure.Credentials;

namespace WebApp.Areas.Default.Controllers
{
    /// <summary>
    /// Контроллер, в котором располагаются различные методы. Если методы накапливается много, то они группируются и для них создается уже отдельный контроллер.
    /// </summary>
    public class CommonController : BaseController
    {
        [Inject]
        public ICommonService CommonService { get; set; }
        [Inject]
        public IAddressesService AddressesService { get; set; }
        [Inject]
        public ICaptcha CaptchaGenerator { get; set; }

        public void Captcha() 
        {
            Response.Clear();
            Response.ContentType = "image/jpeg";
            Session["captcha"] = CaptchaGenerator.Generate(Response.OutputStream);
        }

        public async Task<string> GetAddressByRequestIp() 
        {
            string ip = GetUserIP();
            try
            {
                Address address = await AddressesService.GetAddressByIpAsync(ip);
                return JsonConvert.SerializeObject(address);
            }
            catch (Exception) 
            {
                return "{}";
            }                                 
        }

        public async Task<string> GetCityByIp()
        {
            string ip = GetUserIP();
            string city = await CommonService.GetCityByIpAsync(ip);
            return city;
        }

        public ActionResult TestCaptcha() 
        {
            return View();
        }

        [HttpPost]
        public string TestCaptcha(string captcha)
        {
            return string.Equals(Session["captcha"], captcha) ? "OK" : "NO";
        }

        public ActionResult BlurEffectTest()
        {
            return View();
        }
    }
}

WebApp/Areas/Default/Views/Common/BlurEffectTest.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BlurEffectTest</title>
     <link href="~/Areas/Default/Content/Styles/Site.css" rel="stylesheet" />
    <style>
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <img src="http://st0.InfoShop.club/Images/Products/54538.jpg" style="width: 100%;" />
                <div class="blur-effect-image-holder"> 
                    <img class="blur-effect-image" src="http://st0.InfoShop.club/Images/Products/54537.jpg" />
                    <div class="blur-effect-container"></div>
                    <div class="blur-effect-slider"></div>
                </div>
            </div>
        </div>
    </div>
    <script>
        var jsRoute = "@ViewContext.RouteData.DataTokens["area"].ToString()_@ViewContext.RouteData.Values["controller"].ToString()_@ViewContext.RouteData.Values["action"].ToString()";
    </script>
    <script src="@MvcApplication.UrlUtils.GetBaseUrl()Content/Javascripts/require.js"></script>
    <script src="@MvcApplication.UrlUtils.GetBaseUrl()Content/Javascripts/main.config.js"></script>    
</body>
</html>

WebApp/Areas/Default/Views/Common/TestCaptcha.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TestCaptcha</title>
</head>
<body>
    <div>
        <form method="POST">
            <img src="@Url.Action("Captcha", "Common")" onclick="this.src = this.src.split('?')[0] + '?' + new Date()" style="cursor: pointer;" title="Обновить"/>
            <div class="form-group">
                <label class="col-md-3 control-label">Введите код на картинке</label>
                <div class="col-md-9">
                    <input name="captcha" type="text" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn btn-default">Проверить</button>
                </div>
            </div>
        </form>
    </div>
</body>
</html>